var data = [
  { NBHD_NAME: "Athmar Park", pov_rate: 18.65 },
  { NBHD_NAME: "Auraria", pov_rate: 0 },
  { NBHD_NAME: "Baker", pov_rate: 11 },
  { NBHD_NAME: "Barnum", pov_rate: 27.7 },
  { NBHD_NAME: "Barnum West", pov_rate: 10.3 },
  { NBHD_NAME: "Bear Valley", pov_rate: 6.5 },
  { NBHD_NAME: "Belcaro", pov_rate: 3.3 },
  { NBHD_NAME: "Berkeley", pov_rate: 7.55 },
  { NBHD_NAME: "Capitol Hill", pov_rate: 12 },
  { NBHD_NAME: "CBD", pov_rate: 24 },
  { NBHD_NAME: "Chaffee Park", pov_rate: 9.7 },
  { NBHD_NAME: "Cheesman Park", pov_rate: 9.85 },
  { NBHD_NAME: "Cherry Creek", pov_rate: 5.5 },
  { NBHD_NAME: "City Park", pov_rate: 12 },
  { NBHD_NAME: "City Park West", pov_rate: 14.4 },
  { NBHD_NAME: "Civic Center", pov_rate: 12.1 },
  { NBHD_NAME: "Clayton", pov_rate: 19 },
  { NBHD_NAME: "Cole", pov_rate: 22.1 },
  { NBHD_NAME: "College View / South Platte", pov_rate: 28.5 },
  { NBHD_NAME: "Congress Park", pov_rate: 9.6 },
  { NBHD_NAME: "Cory - Merrill", pov_rate: 6.6 },
  { NBHD_NAME: "Country Club", pov_rate: 2.1 },
  { NBHD_NAME: "DIA", pov_rate: 10.4 },
  { NBHD_NAME: "East Colfax", pov_rate: 18 },
  { NBHD_NAME: "Elyria Swansea", pov_rate: 20.4 },
  { NBHD_NAME: "Five Points", pov_rate: 17.63333333 },
  { NBHD_NAME: "Fort Logan", pov_rate: 10.73333333 },
  { NBHD_NAME: "Gateway / Green Valley Ranch", pov_rate: 8.625 },
  { NBHD_NAME: "Globeville", pov_rate: 29.6 },
  { NBHD_NAME: "Goldsmith", pov_rate: 14.4 },
  { NBHD_NAME: "Hale", pov_rate: 8.1 },
  { NBHD_NAME: "Hampden", pov_rate: 12.875 },
  { NBHD_NAME: "Hampden South", pov_rate: 5.23333333 },
  { NBHD_NAME: "Harvey Park", pov_rate: 14.7 },
  { NBHD_NAME: "Harvey Park South", pov_rate: 12.1 },
  { NBHD_NAME: "Highland", pov_rate: 7.65 },
  { NBHD_NAME: "Hilltop", pov_rate: 4.05 },
  { NBHD_NAME: "Indian Creek", pov_rate: 4.2 },
  { NBHD_NAME: "Jefferson Park", pov_rate: 16.1 },
  { NBHD_NAME: "Kennedy", pov_rate: 11.8 },
  { NBHD_NAME: "Lincoln Park", pov_rate: 35.4 },
  { NBHD_NAME: "Lowry Field", pov_rate: 7.4 },
  { NBHD_NAME: "Mar Lee", pov_rate: 14.1 },
  { NBHD_NAME: "Marston", pov_rate: 7.1 },
  { NBHD_NAME: "Montbello", pov_rate: 13.62857143 },
  { NBHD_NAME: "Montclair", pov_rate: 2.7 },
  { NBHD_NAME: "North Capitol Hill", pov_rate: 12.25 },
  { NBHD_NAME: "North Park Hill", pov_rate: 4.35 },
  { NBHD_NAME: "Northeast Park Hill", pov_rate: 22.4 },
  { NBHD_NAME: "Overland", pov_rate: 13.7 },
  { NBHD_NAME: "Platt Park", pov_rate: 5.6 },
  { NBHD_NAME: "Regis", pov_rate: 16 },
  { NBHD_NAME: "Rosedale", pov_rate: 6.9 },
  { NBHD_NAME: "Ruby Hill", pov_rate: 13.45 },
  { NBHD_NAME: "Skyland", pov_rate: 7.7 },
  { NBHD_NAME: "Sloan Lake", pov_rate: 13.5 },
  { NBHD_NAME: "South Park Hill", pov_rate: 5.9 },
  { NBHD_NAME: "Southmoor Park", pov_rate: 8 },
  { NBHD_NAME: "Speer", pov_rate: 9.03333333 },
  { NBHD_NAME: "Stapleton", pov_rate: 3.65 },
  { NBHD_NAME: "Sun Valley", pov_rate: 76.8 },
  { NBHD_NAME: "Sunnyside", pov_rate: 18.36666667 },
  { NBHD_NAME: "Union Station", pov_rate: 13.9 },
  { NBHD_NAME: "University", pov_rate: 14.1 },
  { NBHD_NAME: "University Hills", pov_rate: 6.1 },
  { NBHD_NAME: "University Park", pov_rate: 16.1 },
  { NBHD_NAME: "Valverde", pov_rate: 18.5 },
  { NBHD_NAME: "Villa Park", pov_rate: 22.5 },
  { NBHD_NAME: "Virginia Village", pov_rate: 14.95 },
  { NBHD_NAME: "Washington Park", pov_rate: 3.95 },
  { NBHD_NAME: "Washington Park West", pov_rate: 6.75 },
  { NBHD_NAME: "Washington Virginia Vale", pov_rate: 13.5 },
  { NBHD_NAME: "Wellshire", pov_rate: 3.2 },
  { NBHD_NAME: "West Colfax", pov_rate: 22.9 },
  { NBHD_NAME: "West Highland", pov_rate: 8.8 },
  { NBHD_NAME: "Westwood", pov_rate: 26.525 },
  { NBHD_NAME: "Whittier", pov_rate: 11.2 },
  { NBHD_NAME: "Windsor", pov_rate: 12.23333333 },
];
